OM-30
gbrlbrbs/omni_manager pull request #10
Opened 2021-11-16 15:59 UTC by Del-23

Implementação das tabelas na tela de dashboard.

2021-11-16 16:05 UTC, Del-23 commented
Arquivos envolvidos (todos na pasta lib/pages/dashboard/ widgets):

projects.dart: tabela referente a projetos

avaliation360.dart tabela referente à valiação 360

A chamada das classes ProjectsTableSimple( ) e  Avaliation360TableSimple( ) ocorre no arquivo dashboard.dart (pasta lib/pages/dashboard).

2021-11-24 13:34 UTC, samuelv8 approved these changes

2021-11-25 21:14 UTC, gbrlbrbs requested changes
Adicionar o campo hardcoded na home e o spreadsheet

2021-11-25 21:23 UTC, gbrlbrbs approved these changes

2021-11-25 21:26 UTC, merged